### ISSUE TITLE
Issue with indexes numbering

### ISSUE THREAD

**Issue by SamuelRiversMoore** [sylvainjule/kirby-categories#4]
Hi Sylvain,
there is an issue with the way you handle the categories indexes when adding a new category...

### How to reproduce it

Let say I have a list of 3 categories with indexes **1**, **2** and **3**. If I remove the category **number 2** which is in in the middle of my list, then if I add a new category, the new category `id` and `panelIndex` will be **3**, which is already taken by the third category of my initial list.  

### How to fix it

I would suggest not using `this.localValue.length` to define the `newIndex` in [`Categories.vue`](https://github.com/sylvainjule/kirby-categories/blob/fcc513ffc359d732fbcaf2f822a1ce35dd010548/src/fields/Categories.vue#L105).

Here are different options :

1. If you want to increment indexes based on the highest existing index :
```
newIndex() {
    const indexes = !this.localValue || !this.localValue.length ? [0] : this.localValue.map((item) => item.panelIndex)
    return Math.max(...indexes) + 1
}
```

2. If you want to fill unused indexes : 
```
newIndex() {
    const indexes = !this.localValue || !this.localValue.length ? [] : this.localValue.map((item) => item.panelIndex)
    for (var i = 1; i <= indexes.length + 1; i++) {
        if (indexes.indexOf(i) == -1) {
            return i
        }
    }
}
```

There is probably better ways of writing this, though...

**Comment by sylvainjule** [comment]
Hi, thank you for the input! Indeed, this is not ideal at all...

Incrementing based on the highest **existing** index isn't neither, because if I delete category number 3 and create a new one with a completely different purpose, I wouldn't want its index to be 3 to prevent colliding with what may have been associated with the previous category 3.

I will push an update where the field keeps track of the highest index that **has existed**, and increment from there.

**Comment by SamuelRiversMoore** [comment]
Thank you for the fix!
